### ISSUE TITLE
did't show the data in artik cloud

### ISSUE THREAD

**Issue by salmanfarisvp** [artikcloud/sample-iot-weatherstation#1]
i only got the output in raspberry pi terminal  when running weathre.js  :`- {"error":{"code":401,"message":"Please provide a valid authorization header"}}`
and nothing in the cloud

**Comment by yujingwu** [comment]
Are you sure you did your setup at ARTIK Cloud? I have enhanced the README. Please revisit README especially the following 
"Before running the above programs, make sure you finish setup at ARTIK Cloud."

**Comment by yujingwu** [comment]
Reopen should you still have a problem. In that case, please provide details about your issue and  your setup and workflows. You should closely follow the instructions in the article mentioned in README.

**Comment by salmanfarisvp** [comment]
yes, I followed all the instructions but , still the error remain

**Comment by yujingwu** [comment]
Sorry just saw your comment. Will assign an engineer to take a close look. Thanks for being patient.

**Comment by yujingwu** [comment]
@jonathanpaek Could you please take a look? Thank You!

**Comment by jonathanpaek** [comment]
@salmanfarisvp replace the device token / and device id in the sample weather.js code with your own values.   authorization header error is associated with incorrect tokens and/or id's. 

As a prereq:  you should have already 1) Add/Connect New Device - https://artik.cloud/my/devices from your artik.cloud dashboard using Temp Sensor as the Device Type.   2) Dashboard will provide you the **Device Id** and generated **Device Token** needed for the sample.   [Reference Weather IoT Documentation](https://www.artik.io/blog/2016/08/make-iot-weather-station-artik-cloud/#connect-to-sami-its-free-really)

weather.js

```
var bearer = "Bearer INSERT_DEVICE_TOKEN_HERE";
var sdid = "INSERT_DEVICE_ID_HERE";
```
